[package]
name = "rust-func"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda_runtime = "0.4"
lambda_http = "0.4.0"
serde_json = "1.0.59"
tokio = "1.11.0"
reqwest = { version = "0.11", features = ["json"] }
openssl = "0.10.41"

[[bin]]
name = "rust-func"
path = "src/rust-func.rs"
